name: ar_qr_scanner
description: ARTools - QR & Barcode Scanner

publish_to: "none"

version: 1.0.1+2

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.6.1
  get: ^4.6.5
  mobile_scanner: ^2.1.0

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
